project:
  title: "Data for Development: Asia"
  type: lirneasia
  render:
    - "reports/*/*.qmd"
    - "!reports/common/*.qmd" # Do not render included files
  post-render: quarto run _scripts/link-pdfs.ts
  
# 1. Global metadata
lang: en-US
date: "October 2025" # Default date, can be overridden in country files
date-format: long
license: "CC BY"

# 3. Tables and lists
toc: true # Table of contents
toc-depth: 3
toc-indent: 1.5em
lof: true # List of figures
lot: true # List of tables

# 3. Numbering and captions
number-sections: true
section-numbering: "1.1"
number-depth: 3
fig-cap-location: bottom
tbl-cap-location: top

# 5. Bibliography and citations
# This loads the MASTER bibliography. 
# Country-specific bibs are merged in the country folder.
bibliography: bibliography/d4dasia-bib.json
csl: bibliography/chicago-shortened-notes-bibliography-subsequent-author.csl
reference-section-title: References
citeproc: true

# 6. Format Settings
format:
  lirneasia-typst:
    # Keeps intermediate files for debugging. 
    # (See note below about .gitignore)
    keep-typ: true 
    keep-md: true

# 7. Editor Preferences
editor:
  render-on-save: true
